#' Class 'pvol': polar volume
#' @param object object of class 'pvol'
#' @param x object of class 'pvol'
#' @param ... additional arguments affecting the summary produced.
#' @export
#' @method summary pvol
#' @details
#' A polar scan object of class 'pvol' is a list containing:
#' \describe{
#'  \item{\code{radar}}{character string with the radar identifier}
#'  \item{\code{datetime}}{nominal time of the volume [UTC]}
#'  \item{\code{scans}}{a list with scan objects of class 'scan'}
#'  \item{\code{attributes}}{list with the volume's \code{\\what}, \code{\\where} and \code{\\how} attributes}
#'  \item{\code{geo}}{geographic data, a list with:
#'   \describe{
#'      \item{\code{lat}}{latitude of the radar [decimal degrees]}
#'      \item{\code{lon}}{longitude of the radar [decimal degrees]}
#'      \item{\code{height}}{height of the radar antenna [metres above sea level]}
#'   }
#'  }
#' }
#' @examples
#' # locate example volume file:
#' pvol <- system.file("extdata", "volume.h5", package="bioRad")
#' # print the local path of the volume file:
#' pvol
#' # load the file:
#' vol=read.pvol(pvol)
#' # print summary info for the loaded polar volume:
#' vol
#' # print summary info for the scans in the polar volume:
#' vol$scans
#' # copy the first scan to a new object 'scan'
#' scan=vol$scans[[1]]
summary.pvol = function(object, ...) print.pvol(object)

#' @rdname summary.pvol
#' @export
#' @return for \code{is.pvol}: \code{TRUE} if its argument is of class "\code{pvol}"
#' @examples
#' is.pvol("this is not a polar volume but a string")  #> FALSE
is.pvol <- function(x) inherits(x, "pvol")


#' print method for class \code{pvol}
#'
#' @param x An object of class \code{pvol}, a polar volume
#' @keywords internal
#' @export
print.pvol=function(x,digits = max(3L, getOption("digits") - 3L), ...){
  stopifnot(inherits(x, "pvol"))
  cat("               Polar volume (class pvol)\n\n")
  cat("     # scans: ",length(x$scans),"\n")
  cat("       radar: ",x$radar,"\n")
  cat("      source: ",x$attributes$what$source,"\n")
  cat("nominal time: ",as.character(x$datetime),"\n\n")
}

#' Read a polar volume (pvol) from file
#'
#' @param filename A string containing the path to a vertical profile generated by \link[bioRad]{calculate_vp}
#' @param sort logical. When \code{TRUE} sort scans ascending by elevation
#' @param param atomic vector of character strings, containing the names of scan parameters to read. To read all scan parameters use 'all'.
#' @param lat latitude in decimal degrees of the radar position. If not specified, value stored in file is used. If specified, value stored in file is overwritten.
#' @param lon longitude in decimal degrees of the radar position. If not specified, value stored in file is used. If specified, value stored in file is overwritten.
#' @param height height of the centre of the antenna in meters above sea level. If not specified, value stored in file is used. If specified, value stored in file is overwritten.
#' @param elangle.min Minimum scan elevation to read in degrees
#' @param elangle.max Maximum scan elevation to read in degrees
#' @param verbose logical. Whether to print messages to console
#' @param mount character string with the mount point (a directory path) for the Docker container
#' @export
#' @return an object of class \link[=summary.pvol]{pvol}, which is a list containing polar scans, i.e. objects of class \code{scan}
#' @details
#' Scan parameters are named according to the OPERA data information model (ODIM), see
#' Table 16 in the \href{https://github.com/adokter/vol2bird/blob/master/doc/OPERA2014_O4_ODIM_H5-v2.2.pdf}{ODIM specification}.
#' Commonly available parameters are:
#' \describe{
#'  \item{"\code{DBZH}", "\code{DBZ}"}{(Logged) reflectivity factor [dBZ]}
#'  \item{"\code{VRADH}", "\code{VRAD}"}{Radial velocity [m/s]. Radial velocities towards
#'   the radar are negative, while radial velocities away from the radar are positive}
#'  \item{"\code{RHOHV}"}{Correlation coefficient [unitless]. Correlation between vertically polarized and horizontally polarized reflectivity factor}
#'  \item{"\code{PHIDP}"}{Differential phase [degrees]}
#'  \item{"\code{ZDR}"}{(Logged) differential reflectivity [dB]}
#' }
#' @examples
#' # locate example volume file:
#' pvol <- system.file("extdata", "volume.h5", package="bioRad")
#' # print the local path of the volume file:
#' pvol
#' # load the file:
#' vol=read.pvol(pvol)
#' # print summary info for the loaded polar volume:
#' vol
#' # print summary info for the scans in the polar volume:
#' vol$scans
#' # copy the first scan to a new object 'scan'
#' scan=vol$scans[[1]]
#' # print summary info for the new object:
#' scan
read.pvol = function(filename,param=c("DBZH","VRADH","VRAD","RHOHV","ZDR","PHIDP","CELL"),sort=T,lat,lon,height,elangle.min=0,elangle.max=90,verbose=T,mount=dirname(filename)){
  if(!is.logical(sort)) stop("'sort' should be logical")
  if(!missing(lat)) if(!is.numeric(lat) || lat< -90 || lat>90) stop("'lat' should be numeric between -90 and 90 degrees")
  if(!missing(lon)) if(!is.numeric(lon) || lat< -360 || lat>360) stop("'lon' should be numeric between -360 and 360 degrees")
  if(!missing(height)) if(!is.numeric(height) || height<0) stop("'height' should be a positive number of meters above sea level")

  # check file type. If not ODIM hdf5, try to convert from RSL
  cleanup=F
  if(H5Fis_hdf5(filename)){
    if(!is.pvolfile(filename)) stop("failed to read hdf5 file")
  }
  else{
    if(verbose) cat("Converting using Docker ...\n")
    if(!docker) stop("Requires a running Docker daemon.\nTo enable, start your local Docker daemon, and run 'check_docker()' in R\n")
    filename = nexrad_to_odim_tempfile(filename,verbose=verbose,mount=mount)
    if(!is.pvolfile(filename)){
      file.remove(filename)
      stop("converted file contains errors")
    }
    cleanup=T
  }

  #extract scan groups
  scans=h5ls(filename,recursive=F)$name
  scans=scans[grep("dataset",scans)]

  #extract elevations, and make selection based on elevation
  elevs=sapply(scans,function(x) h5readAttributes(filename,paste(x,"/where",sep=""))$elangle)
  scans=scans[elevs>=elangle.min & elevs<=elangle.max]

  #extract attributes
  h5struct=h5ls(filename)
  h5struct=h5struct[h5struct$group=="/",]$name
  attribs.how=attribs.what=attribs.where=NULL
  if("how" %in% h5struct) attribs.how=h5readAttributes(filename,"how")
  if("what" %in% h5struct) attribs.what=h5readAttributes(filename,"what")
  if("where" %in% h5struct) attribs.where=h5readAttributes(filename,"where")

  vol.lat=attribs.where$lat
  vol.lon=attribs.where$lon
  vol.height=attribs.where$height
  if(is.null(vol.lat)){
    if(missing(lat)){
      if(cleanup) file.remove(filename)
      stop("latitude not found in file, provide 'lat' argument")
    } else vol.lat=lat
  }
  if(is.null(vol.lon)){
    if(missing(lon)){
      if(cleanup) file.remove(filename)
      stop("longitude not found in file, provide 'lon' argument")
    } else vol.lon=lon
  }
  if(is.null(vol.height)){
    if(missing(height)){
      if(cleanup) file.remove(filename)
      stop("antenna height not found in file, provide 'height' argument")
    } else vol.height=height
  }
  geo=list(lat=vol.lat,lon=vol.lon,height=vol.height)

  #convert some useful metadata
  datetime=as.POSIXct(paste(attribs.what$date, attribs.what$time), format = "%Y%m%d %H%M%S", tz='UTC')
  sources=strsplit(attribs.what$source,",")[[1]]
  radar=gsub("RAD:","",sources[which(grepl("RAD:",sources))])

  #read scan groups
  data=lapply(scans,function(x) read.scan(filename,x,param,radar,datetime,geo))
  #order by elevation
  if(sort) data=data[order(sapply(data,elangle))]

  #prepare output
  output=list(radar=radar,datetime=datetime,scans=data,attributes=list(how=attribs.how,what=attribs.what,where=attribs.where),geo=geo)
  class(output) = "pvol"

  if(cleanup) file.remove(filename)

  output
}

read.scan=function(filename,scan,param,radar,datetime,geo){
  h5struct=h5ls(filename)
  h5struct=h5struct[h5struct$group==paste("/",scan,sep=""),]$name
  groups=h5struct[grep("data",h5struct)]

  # select which scan parameters to read
  if(length(param)==1 && param=="all") allParam=T else allParam=F
  if(!allParam){
    quantityNames=sapply(groups,function(x) h5readAttributes(filename,paste(scan,"/",x,"/what",sep=""))$quantity)
    groups=groups[quantityNames %in% param]
    if(length(groups)==0) stop(paste("none of the requested scan parameters present in",filename))
  }

  # read attributes

  attribs.how=attribs.what=attribs.where=NULL
  if("how" %in% h5struct) attribs.how=h5readAttributes(filename,paste(scan,"/how",sep=""))
  if("what" %in% h5struct) attribs.what=h5readAttributes(filename,paste(scan,"/what",sep=""))
  if("where" %in% h5struct) attribs.where=h5readAttributes(filename,paste(scan,"/where",sep=""))

  # add attributes to geo list
  geo$elangle=attribs.where$elangle
  geo$rscale=attribs.where$rscale
  geo$ascale=360/attribs.where$nrays

  # read scan parameters
  quantities=lapply(groups,function(x) read.quantity(filename,paste(scan,"/",x,sep=""),radar,datetime,geo))
  quantityNames=sapply(quantities,'[[',"quantityName")
  quantities=lapply(quantities,'[[',"quantity")
  names(quantities)=quantityNames

  output=list(radar=radar,datetime=datetime,params=quantities,attributes=list(how=attribs.how,what=attribs.what,where=attribs.where),geo=geo)
  class(output)="scan"
  output
}

read.quantity=function(filename,quantity,radar,datetime,geo){
  data=h5read(filename,quantity)$data
  attr=h5readAttributes(filename,paste(quantity,"/what",sep=""))
  data=replace(data,data==as.numeric(attr$nodata),NA)
  data=replace(data,data==as.numeric(attr$undetect),NaN)
  data=as.numeric(attr$offset)+as.numeric(attr$gain)*data
  class(data)=c("param",class(data))
  attributes(data)$radar=radar
  attributes(data)$datetime=datetime
  attributes(data)$geo=geo
  attributes(data)$param=attr$quantity
  list(quantityName=attr$quantity,quantity=data)
}
