#' Class 'vp': vertical profile
#'
#' Class for vertical profiles
#' @param object object of class 'vp'
#' @param x object of class 'vp'
#' @param ... additional arguments affecting the summary produced.
#' @export
#' @rdname summary.vp
#' @method summary vp
#' @details
#' An object of class \code{vp} contains a vertical profile. A vertical profile contains a collection of quantities,
#'  with each quantity having values at different altitude layers above the earth's surface,
#'  typically equally spaced altitudinal layers.
#'
#' Data contained in this class object should be accessed with the \link{fetch} function.
#' Information stored under \code{attributes} (see below) can be accessed directly.
#'
#' A \code{vp} object is a list containing
#' \describe{
#'  \item{\strong{\code{radar}}}{the radar identifier}
#'  \item{\strong{\code{datetime}}}{the nominal time of the profile}
#'  \item{\strong{\code{data}}}{the profile data, a list containing:
#'    \describe{
#'        \item{\code{HGHT}}{height above mean sea level [m]. Alt. bin from HGHT to HGHT+interval)}
#'        \item{\code{u}}{speed component west to east [m/s]}
#'        \item{\code{v}}{speed component north to south [m/s]}
#'        \item{\code{w}}{vertical speed (unreliable!) [m/s]}
#'        \item{\code{ff}}{horizontal speed [m/s]}
#'        \item{\code{dd}}{direction [degrees, clockwise from north]}
#'        \item{\code{sd_vvp}}{VVP radial velocity standard deviation [m/s]}
#'        \item{\code{gap}}{Angular data gap detected [T/F]}
#'        \item{\code{dbz}}{Bird reflectivity factor [dBZ]}
#'        \item{\code{eta}}{Bird reflectivity [cm^2/km^3]}
#'        \item{\code{dens}}{Bird density [birds/km^3]}
#'        \item{\code{DBZH}}{Total reflectivity factor (bio+meteo scattering) [dBZ]}
#'        \item{\code{n}}{number of points VVP bird velocity analysis (u,v,w,ff,dd)}
#'        \item{\code{n_all}}{number of points VVP st.dev. estimate (sd_vvp)}
#'        \item{\code{n_dbz}}{number of points bird density estimate (dbz,eta,dens)}
#'        \item{\code{n_dbz_all}}{number of points total reflectivity estimate (DBZH)}
#'    }
#'  }
#'  \item{\strong{\code{attributes}}}{list with the profile's \code{\\what}, \code{\\where} and \code{\\how} attributes}
#' }
summary.vp=function(object, ...) print.vp(object)

#' @rdname summary.vp
#' @export
#' @return for \code{is.vp}: \code{TRUE} if its argument is of class "\code{vp}"
is.vp <- function(x) inherits(x, "vp")

#' @rdname summary.vp
#' @export
#' @return for \code{dim.vp}: dimensions of the profile data
dim.vp <- function(x) {
  stopifnot(inherits(x,"vp"))
  dim(x$data)
}

#' print method for class \code{vp}
#'
#' @param x An object of class \code{vp}, like the result of a call to \link[=summary.vp]{readvp}
#' @keywords internal
#' @export
print.vp=function(x,digits = max(3L, getOption("digits") - 3L), ...){
  stopifnot(inherits(x, "vp"))
  cat("               Vertical profile (class vp)\n\n")
  cat("       radar: ",x$radar,"\n")
  cat("      source: ",x$attributes$what$source,"\n")
  cat("nominal time: ",as.character(x$datetime),"\n")
  cat("generated by: ",paste(x$attributes$how$task,x$attributes$how$task_version),"\n")
}

#' Read a vertical profile (vp) from file
#'
#' @param filename A string containing the path to a vertical profile generated by \link{vol2bird}
#' @export
#' @return an object of class \link{summary.vp}
#' @examples
#' # locate example profile file:
#' prof <- system.file("extdata", "profile.h5", package="bioRad")
#' # print the local path of the profile file:
#' prof
#' # load the file:
#' readvp(prof)
#'
readvp = function(filename){
  if(!is.vpfile(filename)){
    warning(paste(filename,"is not a vertical profile"))
    return(NULL)
  }
  #check input argument
  groups=h5ls(filename,recursive=F)$name
  if(!("dataset1" %in% groups)){
    stop("HDF5 file does not contain a /dataset1 group")
  }
  #extract quantities
  groups=h5ls(filename)
  groups=groups[which(groups$name=="data"),]$group
  quantities=sapply(groups,function(x) quantityName(filename,x))
  profile=as.data.frame(lapply(groups,function(x) readOdimProfileData(filename,x)))
  names(profile)=quantities

  #extract attributes
  attribs.how=h5readAttributes(filename,"how")
  attribs.what=h5readAttributes(filename,"what")
  attribs.where=h5readAttributes(filename,"where")
  #add vp_filename attribute if missing
  if(is.null(attribs.how$filename_vp)) attribs.how$filename_vp=filename

  #convert some useful metadata
  datetime=as.POSIXct(paste(attribs.what$date, attribs.what$time), format = "%Y%m%d %H%M%S", tz='UTC')
  sources=strsplit(attribs.what$source,",")[[1]]
  radar=gsub("NOD:","",sources[which(grepl("NOD:",sources))])
  if(length(radar)==0){
    radar=gsub("RAD:","",sources[which(grepl("RAD:",sources))])
    if(length(radar)==0){
      radar=gsub("WMO:","",sources[which(grepl("WMO:",sources))])
      if(length(radar)==0){
        radar="unknown"
      }
    }
  }

  #prepare output
  output=list(radar=radar,datetime=datetime,data=profile,attributes=list(how=attribs.how,what=attribs.what,where=attribs.where))
  class(output) = "vp"
  output
}

#' Read a list of vertical profiles from multiple files
#'
#' @param files A string vector containing the filenames of vertical profiles in ODIM HDF5 format generated by \link{vol2bird}
#' @export
#' @return an object of class \code{vplist}, which is a list \code{vp} objects
#' @examples
#' \dontrun{readvp(c("my/path/profile1.h5","my/path/profile2.h5", ...))}
#'
readvp.list=function(files){
  vps=lapply(files,readvp)
  # remove nulls
  vps <- vps[!sapply(vps, is.null)]
  do.call(c.vp,vps)
}

#' Read vertical profiles from vol2bird stdout
#'
#' @param file A text file containing the standard output (stdout) generated by vol2bird
#' @param radar string containing a radar identifier
#' @param wavelength radar wavelength in cm, or one of 'C' or 'S' for C-band and S-band radar, respectively
#' @export
#' @return an object inhereting from class "\code{vpts}", see \link{vpts} for details
#' @examples
#' # locate example file:
#' VPtable <- system.file("extdata", "VPtable.txt", package="bioRad")
#' # load time series:
#' ts=readvp.table(VPtable,radar="KBGM", wavelength='S')
#' ts
readvp.table=function(file,radar,wavelength='C'){
  if(!file.exists(file)) stop(paste("file",file,"doesn't exist"))
  if(file.size(file)==0) stop(paste("file",file,"is empty"))
  if(missing(radar)) stop("'radar' argument missing. Required to specify a radar identifier")
  if(missing(wavelength)) warning(paste("No 'wavelength' argument provided, assuming radar operates at ",wavelength,"-band",sep=""))
  if(wavelength=='C') wavelength=5.3
  if(wavelength=='S') wavelength=10.6
  if(!is.numeric(wavelength) || length(wavelength)>1) stop("not a valid 'wavelength' argument")
  #header of the data file
  header.names.short=c("Date","Time","HGHT","u","v","w","ff","dd","sd_vvp","gap","dbz","eta","dens","DBZH","n","n_dbz","n_all","n_dbz_all")
  header.names.long=c("Date","Time","HGHT","u","v","w","ff","dd","sd_vvp","head_bl","head_ff","head_dd","head_sd","gap","dbz","eta","dens","DBZH","n","n_dbz","n_all","n_dbz_all")
  #read the data
  data=read.table(file=file, header = F)
  if(ncol(data)==22) colnames(data)=header.names.long else colnames(data)=header.names.short
  # convert Time into a POSIXct date-time
  data$datetime <- as.POSIXct(paste(data$Date, sprintf('%04d', data$Time), sep = ""), format = "%Y%m%d%H%M", tz='UTC')
  data$Date<-NULL
  data$Time<-NULL
  # sort
  data=data[with(data, order(datetime, HGHT)),]
  # remove duplicates
  data=unique(data)
  # split into profiles
  data=split(data,data$datetime)
  names(data)<-NULL
  # verify that profiles can be flattened
  datadim=sapply(1:length(data), function(x) dim(data[[x]]))
  if(length(unique(datadim[1,]))>1){
    mostFrequent=sort(table(datadim[1,]),decreasing=T)[1]
    if(mostFrequent<=1) stop("Profiles are of unequal altitudinal dimensions, unable to merge")
    mostFrequentNBins=as.integer(names(mostFrequent))
    warning(paste("Profiles are of unequal altitudinal dimensions or contain duplicates. Discarding",length(data)-mostFrequent,"of",length(data),"profiles, restricting to",mostFrequentNBins,"altitude bins."))
    data=data[datadim[1,]==mostFrequentNBins]
  }
  # strip the datetime field
  dates=.POSIXct(sapply(1:length(data),function(x) data[[x]]$datetime[1]),tz="UTC")
  data=lapply(data, function(x) { x["datetime"] <- NULL; x })
  # check whether the time series is regular
  difftimes=difftime(dates[-1],dates[-length(dates)],units="secs")
  if(length(unique(difftimes))==1) regular = T else regular = F
  # flatten the profiles
  profile.quantities=names(data[[1]])
  vpsFlat=lapply(profile.quantities, function(quantity) sapply(data,'[[',quantity))
  names(vpsFlat)=profile.quantities
  vpsFlat$HGHT<-NULL
  # prepare output
  heights=data[[1]]$"HGHT"
  interval=unique(heights[-1]-heights[-length(heights)])

  attributes=list(where=data.frame(interval=interval,levels=length(heights)),how=data.frame(wavelength=wavelength))
  output=list(radar=radar,dates=dates,heights=heights,daterange=.POSIXct(c(min(dates),max(dates)),tz="UTC"),timesteps=difftimes,data=vpsFlat,attributes=attributes,regular=regular)
  class(output)="vpts"
  output
}

readOdimProfileData = function(file,group){
  whatgroup=h5readAttributes(file,sprintf("%s/what",group))
  nodata=whatgroup$nodata
  undetect=whatgroup$undetect
  gain=whatgroup$gain
  offset=whatgroup$offset
  data=h5read(file,sprintf("%s/data",group))[1,]
  data=replace(data,data==nodata,NA)
  data=replace(data,data==undetect,NaN)
  offset+gain*data
}

quantityName = function(file,group){
  whatgroup=h5readAttributes(file,paste(group,"/what",sep=""))
  whatgroup$quantity
}

