#' Inspect vertically integrated profiles (`vpi`)
#'
#' R base functions for inspecting vertically integrated profiles of biological targets
#' (`vp`) object.
#'
#' @param object A `vpi` object.
#' @param ... Additional arguments affecting the summary produced.
#'
#' @method summary vpi
#'
#' @export
#'
#' @details
#' A vpi object is a specially classed data frame generated by function \link{integrate_profile} with the following
#' quantities:
#' \describe{
#'    \item{\code{datetime}}{POSIXct date of each profile in UTC}
#'    \item{\code{vid}}{Vertically Integrated Density in individuals/km^2.
#'       \code{vid} is a surface density, whereas \code{dens} in \code{vp}
#'       objects is a volume density.}
#'    \item{\code{vir}}{Vertically Integrated Reflectivity in cm^2/km^2}
#'    \item{\code{mtr}}{Migration Traffic Rate in individuals/km/h}
#'    \item{\code{rtr}}{Reflectivity Traffic Rate in cm^2/km/h}
#'    \item{\code{mt}}{Migration Traffic in individuals/km, cumulated from
#'       the start of the time series up to \code{datetime}}
#'    \item{\code{rt}}{Reflectivity Traffic in cm^2/km, cumulated from
#'       the start of the time series up to \code{datetime}}
#'    \item{\code{ff}}{Horizontal ground speed in m/s}
#'    \item{\code{dd}}{Horizontal ground speed direction in degrees}
#'    \item{\code{u}}{Ground speed component west to east in m/s}
#'    \item{\code{v}}{Ground speed component south to north in m/s}
#'    \item{\code{height}}{Mean flight height (height weighted by eta) in m above sea level}
#' }
#' Class vpi inherits from class data.frame
#'
#' @seealso
#' * [integrate_profile()]
#' * [plot.vpi()]
#'
#' @examples
#' # Load the example vertical profile time series and integrate to a vpi
#' vpi <- integrate_profile(example_vpts)
#'
#' # Verify that it is an object of class vpi
#' is.vpi(vpi)
#'
#' # Get summary info
#' summary(vpi)
summary.vpi <- function(object, ...) {
  stopifnot(inherits(object, "vpi"))
  cat("               Vertically integrated profile(s) (class vpi)\n\n")
  cat("           radar: ", attributes(object)$radar, "\n")
  cat("      # profiles: ", length(object$datetime), "\n")
  cat("time range (UTC): ", format(min(object$datetime), "%Y-%m-%d %H:%M:%S"),
    "-", format(max(object$datetime), "%Y-%m-%d %H:%M:%S"), "\n"
  )
}

#' Verify if an object is of class `vpi`
#'
#' @param x A `vpi` object.
#'
#' @return For [is.vpi()]: `TRUE` for an object of class `vpi`, otherwise
#'   `FALSE`.
#'
#' @rdname summary.vpi
#'
#' @export
is.vpi <- function(x) {
  inherits(x, "vpi")
}
